# Database and workspace configuration
MOOCdb:
  database: moocdb # default database name
  work_dir: /app/ # do not change this
  MLC_folder: MOOC-Learner-Curated # do not change this
  MLQ_folder: MOOC-Learner-Quantified # do not change this
  MLM_folder: MOOC-Learner-Modeled # do not change this
  MLV_folder: MOOC-Learner-Visualized # do not change this

# MySQL server configuration, do not change this 
mysql:
  host: localhost # do not change this
  port: 3306 # do not change this
  user: root # do not change this

# Redis server configuration, do not change this
redis:
  host: redis
  port: 6379
  db: 0

# Pipeline configuration
# For each pipe, "yes"/"no" means that run/ignore this step
# config the full pipeline
full_pipeline:
    MLC: yes
    MLQ: no
    MLM: no
    MLV: no
# config the MOOC-Learer-Curated pipeline
MLC_pipeline:
  folder_setup: yes
  apipe: yes
  qpipe:
    qpipe_process_events: yes
    qpipe_create_db: yes
    qpipe_populate_db: yes
  curation: yes
  vismooc_extensions:
    vismooc_process:  no
    vismooc_populate: no
  newmitx_extensions:
    newmitx_process: no
    newmitx_populate: no
# config the MOOC-Learer-Quantified pipeline
MLQ_pipeline:
  preprocess: no
  timeout: 1000
  skip:
  is_testing: yes
  test:

# Raw data file tree configuration
data_file:
  data_dir: /data # do not change this, this is the path inside the containers
  course_name_prefix: synthetic
  # change the following suffixes to recognize the course raw data files automatically
  log_file: log_data.json
  vismooc_file:
    course_structure_file: course_structure-prod-analytics.json
    course_certificates_file: certificates_generatedcertificate-prod-analytics.sql
    course_enrollment_file: student_courseenrollment-prod-analytics.sql
    course_user_file: auth_user-prod-analytics.sql
    course_profile_file: auth_userprofile-prod-analytics.sql
    course_forum_file: prod.mongo
  newmitx_file:
    course_video_axis_file: video_axis.json
    course_video_stats_file: video_stats.json
    course_video_stats_day_file: video_stats_day.json
    course_pc_day_totals_file: pc_day_totals.json
    course_person_course_day_file: person_course_day.json
    course_person_course_video_watched_file: person_course_video_watched.json
    course_stats_activity_by_day_file: stats_activity_by_day.json
    course_stats_overall_file: stats_overall.json
    course_time_on_task_file: time_on_task.json
    course_time_on_task_totals_file: time_on_task_totals.json
    course_user_info_combo_file: user_info_combo.json

# Specification of the Open edX logs
open_edx_spec:
  # HKUSTx/MITx
  video_id_spec: HKUSTx
